### ISSUE TITLE
Text not displaying

### ISSUE THREAD

**Issue by SwiftfulThinking** [edudnyk/LabelKit#1]
Hi Eugene, I'm trying to implement LabelKit in to a project - I love the concept.

However, I'm having an issue where the LKLabelLayer is appearing on my final video but the attributedText won't show. Am I not initializing the layer correctly? I just want the text to show for the duration of the video (without animations) for now. My below code results in a red layer (background color) without text. I tried calling setNeedsDisplay / displayIfNeeded but nothing is working.

```
        let textLayer = LKLabelLayer()
        //layer.setNeedsDisplay()
        //textLayer.setNeedsLayout()
        
        let font = UIFont(descriptor: fontOption.fontDescriptor, size: 50)
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: textColor.cgColor,
        ]
        let attributedText = NSAttributedString(string: title, attributes: attributes)
        
        textLayer.attributedText = attributedText
        textLayer.backgroundColor = UIColor.red.cgColor

        //layer.displayIfNeeded()
        //textLayer.displayIfNeeded()

```

**Comment by SwiftfulThinking** [comment]
Any update?

**Comment by edudnyk** [comment]
Hey @PureBreadd, it seems that you don't set the size to the layer. Could you please confirm that the layer's `bounds` are not empty?

**Comment by edudnyk** [comment]
Closed due to insufficient feedback.
